dist: trusty
sudo: true 
language: 'php'

matrix:
    include:
        - php: 7.1

install:   
    - composer install --no-interaction --no-scripts

script:
    - ./vendor/bin/phpunit --filter '::testWithoutDataProvider$' tests/ExampleTest.php
    - ./vendor/bin/phpunit --filter '/::testWithoutDataProvider .*$/' tests/ExampleTest.php
    - ./vendor/bin/phpunit --filter '::testWithoutDataProvider' tests/ExampleTest.php
    - ./vendor/bin/phpunit --filter '::testWithDataProvider$' tests/ExampleTest.php
    - ./vendor/bin/phpunit --filter '/::testWithDataProvider .*$/' tests/ExampleTest.php
    - ./vendor/bin/phpunit --filter '::testWithDataProvider' tests/ExampleTest.php
